FROM node:25-alpine3.22

RUN apk update
RUN apk add openssl

WORKDIR /app

ARG VITE_FRONTEND_URL
ARG VITE_API_URL
ARG VITE_WALLETCONNECT_PROJECT_ID
ARG VITE_GITHUB_CLIENT_ID
ARG VITE_ORCID_CLIENT_ID
ARG VITE_BITBUCKET_CLIENT_ID
ARG VITE_GITLAB_CLIENT_ID
ARG VITE_ORCID_DOMAIN

ENV VITE_FRONTEND_URL=$VITE_FRONTEND_URL
ENV VITE_API_URL=$VITE_API_URL
ENV VITE_WALLETCONNECT_PROJECT_ID=$VITE_WALLETCONNECT_PROJECT_ID
ENV VITE_GITHUB_CLIENT_ID=$VITE_GITHUB_CLIENT_ID
ENV VITE_ORCID_CLIENT_ID=$VITE_ORCID_CLIENT_ID
ENV VITE_BITBUCKET_CLIENT_ID=$VITE_BITBUCKET_CLIENT_ID
ENV VITE_GITLAB_CLIENT_ID=$VITE_GITLAB_CLIENT_ID
ENV VITE_ORCID_DOMAIN=$VITE_ORCID_DOMAIN

COPY . ./
RUN npm install
RUN cd backend && npx prisma generate
RUN npm run build

CMD ["npm", "start"]
# CMD ["sleep", "inf"]
