FROM node:25-alpine3.22

RUN apk update
RUN apk add openssl

WORKDIR /app

ARG VITE_TEST_INSTANCE
ARG VITE_FRONTEND_URL
ARG VITE_API_URL
ARG VITE_WALLETCONNECT_PROJECT_ID
ARG VITE_ORCID_DOMAIN

ENV VITE_TEST_INSTANCE=$VITE_TEST_INSTANCE
ENV VITE_FRONTEND_URL=$VITE_FRONTEND_URL
ENV VITE_API_URL=$VITE_API_URL
ENV VITE_WALLETCONNECT_PROJECT_ID=$VITE_WALLETCONNECT_PROJECT_ID
ENV VITE_ORCID_DOMAIN=$VITE_ORCID_DOMAIN

COPY . ./
RUN npm install
RUN cd backend && npx prisma generate
RUN npm run build

ENTRYPOINT [ "./scripts/fly.io-entrypooint.sh" ]
