[dependencies]
identify = "0.0.2"

[toolchain]
moc = "0.16.3"

[canisters.core_canister]
main = "canisters/core/main.mo"
candid = "canisters/core/core_canister.did"

[canisters.core_canister.check-stable]
path = "deployed/core_canister.most"

[canisters.workflow_canister]
main = "canisters/workflow/main.mo"
candid = "canisters/workflow/workflow_canister.did"

[canisters.workflow_canister.check-stable]
path = "deployed/workflow_canister.most"

[canisters.treasury_canister]
main = "canisters/treasury/main.mo"
candid = "canisters/treasury/treasury_canister.did"

[canisters.treasury_canister.check-stable]
path = "deployed/treasury_canister.most"

[canisters.archive_router]
main = "canisters/archive_router/main.mo"
candid = "canisters/archive_router/archive_router.did"

[canisters.archive_router.check-stable]
path = "deployed/archive_router.most"

[canisters.oauth_fixture]
main = "canisters/oauth_fixture/main.mo"
candid = "canisters/oauth_fixture/oauth_fixture.did"

[canisters.oauth_fixture.check-stable]
path = "deployed/oauth_fixture.most"
