#!/bin/sh

set -ex

npm run build
npm test

cd backend

# To avoid prisma errors.
npm run db:generate

# Prevent submitting, if has not been tested on a local DB.
npx prisma migrate status --config prisma/prisma.config.js

# Prevent submitting if not all migrations have been applied.
npx prisma migrate diff --from-schema prisma/schema.prisma --to-migrations prisma/migrations --exit-code
