# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'meritocracy'
primary_region = 'iad'
# swap_size_mb = 512  # Machines with swap are not eligible to suspend

[deploy]
# TODO@P3 Having more than one machine would lead to duplicate cron tasks executing
# and to keep-alive ping going to a wrong machine.
# As a temporary solution, I remove the duplicators and leave just one machine deployed.
strategy = "rolling" # "bluegreen" # TODO@P3: Neither makes zero downtime :-(
max_unavailable = 1

[build]

[env]
API_URL = 'https://api.merit.science-dao.org'
BITBUCKET_CLIENT_ID = 'PFdcCeTaGXXY723bfBuTe3deVJDstaf2'
BITCOIN_ENABLED = 'true'
ENABLE_BCH = 'true'
BITCOIN_RPC_PASSWORD = ''
BITCOIN_RPC_URL = 'http://localhost:8332'
BITCOIN_RPC_USERNAME = ''
ETHEREUM_MAINNET_ENABLED = 'true'
ETHEREUM_CELO_ENABLED = 'true'
ETHEREUM_CELO_RPC_URL = 'https://celo-json-rpc.stakely.io'
ETHEREUM_POLYGON_ENABLED = 'true'
ETHEREUM_ARBITRUM_ENABLED = 'true'
ETHEREUM_OPTIMISM_ENABLED = 'true'
ETHEREUM_BASE_ENABLED = 'true'
ICP_ENABLED = 'true'
MEZO_ENABLED = 'true'
COSMOS_ENABLED = 'true'
COSMOS_RPC_URL = 'https://cosmos-rpc.publicnode.com:443'
DIDIT_APP_ID = 'a4efc76a-f3bf-4e99-84c2-859718ad1827'
DIDIT_WORKFLOW_RECEIVING_ID = '08d10959-db0e-485f-a21f-f20d347d992a'
DIDIT_WORKFLOW_VOTING_ID = '00514a1a-aa74-47a6-a50f-fe4722952b86'
FRONTEND_URL = 'https://merit.science-dao.org'
GITHUB_CLIENT_ID = 'Iv23liACVkYe3qylnSpT'
GITLAB_CLIENT_ID = '8a8b4b40b8d3d78ccde78b4c80ffd69db99ca6f022a42ac0159ab21c8d148da6'
HEDERA_ENABLED = 'true'
HEDERA_RPC_URL = 'https://mainnet.hashio.io/api'
ETHEREUM_SEPOLIA_ENABLED = 'true'
# ETHEREUM_LOCALHOST_ENABLED = 'true'
INSTALLATION_UID = 'be98a57d-2dd6-4088-9b85-b232fd4bdb65'
# MEZO_TESTNET_ENABLED = 'true'
# MEZO_TESTNET_RPC_URL = 'https://rpc.test.mezo.org'
NODE_ENV = 'production'
OPENAI_FLEX_MODE = 'nonbatch'
OPENAI_MODEL = 'gpt-5-mini'
OPENAI_NO_REASONING = 'yes'
OPENAI_OVERRIDE_MAX_TOOL_CALLS = '6'
OPENAI_OVERRIDE_REASONING_EFFORT = 'medium'
OPEN_AI_FAKE = 'false'
ORCID_CLIENT_ID = 'APP-CNFU262DB2VL0XQ3'
ORCID_DOMAIN = 'orcid.org'
POLKADOT_ENABLED = 'true'
POLKADOT_RPC_URL = 'https://rpc.polkadot.io'
PORT = '3001'
SKIP_KYC = 'false'
SMTP_HOST = 'smtp-relay.brevo.com'
SMTP_PORT = '587'
SMTP_SECURE = 'false'
SMTP_SENDER_EMAIL = 'noreply@vporton.name'
SMTP_USER = 'porton.victor@gmail.com'
SOLANA_ENABLED = 'true'
SOLANA_RPC_URL = 'https://api.mainnet-beta.solana.com'
STELLAR_ENABLED = 'true'
STELLAR_HORIZON_URL = 'https://horizon.stellar.org'
STELLAR_NETWORK_PASSPHRASE = 'Public Global Stellar Network ; September 2015'
ICP_CKBTC_LEDGER_CANISTER_ID = 'mxzaz-hqaaa-aaaar-qaada-cai'
ICP_CKETH_LEDGER_CANISTER_ID = 'ss2fx-dyaaa-aaaar-qacoq-cai'
ICP_CKETH_HELPER_CONTRACT_ADDRESS = '0x6abDA0438307733FC299e9C229FD3cc074bD8cC0'
ICP_CKUSDT_LEDGER_CANISTER_ID = 'cngnf-vqaaa-aaaar-qag4q-cai'
ICP_CKUSDT_ERC20_CONTRACT_ADDRESS = ''
ICP_CKUSDC_LEDGER_CANISTER_ID = 'xevnm-gaaaa-aaaar-qafnq-cai'
ICP_CKUSDC_ERC20_CONTRACT_ADDRESS = ''
ICP_CKEURC_LEDGER_CANISTER_ID = 'pe5t5-diaaa-aaaar-qahwa-cai'
ICP_CKEURC_ERC20_CONTRACT_ADDRESS = ''

[[services]]
protocol = 'tcp'
internal_port = 3001
auto_stop_machines = 'suspend'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[services.ports]]
port = 80
handlers = ['http']
force_https = true

[[services.ports]]
port = 443
handlers = ['tls', 'http']

[[services.tcp_checks]]
interval = '2s'
timeout = '2s'
grace_period = '60s'

[[vm]]
# memory = '512mb'  # not enough
memory = '1024mb'  # <=2GB to be eligible for suspend
cpus = 1
memory_mb = 512
