-- Current PostgreSQL schema reconstructed from Prisma schema and committed migrations.
-- Source of truth examined: backend/prisma/schema.prisma; backend/prisma/migrations/*/migration.sql.
-- This is a normalized descriptive DDL, not a replacement migration.  All identifiers are quoted
-- because Prisma created quoted mixed-case columns. `updatedAt` is written by Prisma, not a DB trigger.

CREATE TABLE "users" ("id" SERIAL PRIMARY KEY, "email" TEXT UNIQUE, "emailVerified" BOOLEAN NOT NULL DEFAULT false, "votingPleaUnsubscribed" BOOLEAN NOT NULL DEFAULT false, "name" TEXT, "ethereumAddress" TEXT UNIQUE, "solanaAddress" TEXT, "bitcoinAddress" TEXT, "bitcoinCashAddress" TEXT, "polkadotAddress" TEXT, "cosmosAddress" TEXT, "stellarAddress" TEXT, "icpAddress" TEXT, "orcidId" TEXT UNIQUE, "githubHandle" TEXT UNIQUE, "bitbucketHandle" TEXT UNIQUE, "gitlabHandle" TEXT UNIQUE, "onboarded" BOOLEAN NOT NULL DEFAULT false, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "bannedTill" TIMESTAMP(3), "evaluationBlockedTill" TIMESTAMP(3), "evaluationBlockReason" TEXT, "paymentHoldStartedAt" TIMESTAMP(3), "compensationDueAt" TIMESTAMP(3), "lastPaymentAmount" DECIMAL(65,30), "shareInGDP" DOUBLE PRECISION, "isDeleted" BOOLEAN NOT NULL DEFAULT false, "deletedAt" TIMESTAMP(3), "kycStatus" TEXT, "kycVerifiedAt" TIMESTAMP(3), "kycRejectedAt" TIMESTAMP(3), "kycRejectionReason" TEXT, "kycData" TEXT, "kycVotingStatus" TEXT, "kycVotingVerifiedAt" TIMESTAMP(3), "kycVotingRejectedAt" TIMESTAMP(3), "kycVotingRejectionReason" TEXT, "kycVotingData" TEXT, "issuingState" TEXT, "personalNumber" TEXT, "residenceCountry" TEXT, UNIQUE ("issuingState", "personalNumber"));
CREATE INDEX "users_onboarded_idx" ON "users" ("onboarded"); CREATE INDEX "users_onboarded_shareInGDP_idx" ON "users" ("onboarded", "shareInGDP" DESC); CREATE INDEX "users_shareInGDP_idx" ON "users" ("shareInGDP"); CREATE INDEX "users_evaluationBlockedTill_idx" ON "users" ("evaluationBlockedTill"); CREATE INDEX "users_paymentHoldStartedAt_idx" ON "users" ("paymentHoldStartedAt"); CREATE INDEX "users_compensationDueAt_idx" ON "users" ("compensationDueAt"); CREATE INDEX "users_kycStatus_idx" ON "users" ("kycStatus"); CREATE INDEX "users_cosmosAddress_idx" ON "users" ("cosmosAddress"); CREATE INDEX "users_icpAddress_idx" ON "users" ("icpAddress");

CREATE TABLE "user_emails" ("id" SERIAL PRIMARY KEY, "userId" INTEGER NOT NULL REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE, "email" TEXT NOT NULL UNIQUE, "verified" BOOLEAN NOT NULL DEFAULT false, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL); CREATE INDEX "user_emails_userId_idx" ON "user_emails" ("userId"); CREATE INDEX "user_emails_userId_verified_idx" ON "user_emails" ("userId", "verified");
CREATE TABLE "sessions" ("id" TEXT PRIMARY KEY, "userId" INTEGER NOT NULL REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE, "token" TEXT NOT NULL UNIQUE, "expiresAt" TIMESTAMP(3) NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL); CREATE INDEX "sessions_userId_idx" ON "sessions" ("userId"); CREATE INDEX "sessions_expiresAt_idx" ON "sessions" ("expiresAt");
CREATE TABLE "email_verification_tokens" ("id" TEXT PRIMARY KEY, "token" TEXT NOT NULL UNIQUE, "email" TEXT NOT NULL, "userId" INTEGER NOT NULL REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE, "expiresAt" TIMESTAMP(3) NOT NULL, "used" BOOLEAN NOT NULL DEFAULT false, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL); CREATE INDEX "email_verification_tokens_userId_idx" ON "email_verification_tokens" ("userId"); CREATE INDEX "email_verification_tokens_expiresAt_idx" ON "email_verification_tokens" ("expiresAt"); CREATE INDEX "email_verification_tokens_used_idx" ON "email_verification_tokens" ("used");
CREATE TABLE "kyc_tokens" ("id" TEXT PRIMARY KEY, "token" TEXT NOT NULL UNIQUE, "userId" INTEGER NOT NULL REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE, "expiresAt" TIMESTAMP(3) NOT NULL, "used" BOOLEAN NOT NULL DEFAULT false, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL); CREATE INDEX "kyc_tokens_userId_idx" ON "kyc_tokens" ("userId"); CREATE INDEX "kyc_tokens_expiresAt_idx" ON "kyc_tokens" ("expiresAt"); CREATE INDEX "kyc_tokens_used_idx" ON "kyc_tokens" ("used");
CREATE TABLE "ban_votes" ("id" SERIAL PRIMARY KEY, "voterUserId" INTEGER NOT NULL REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE, "targetUserId" INTEGER NOT NULL REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE, "message" TEXT NOT NULL, "type" TEXT NOT NULL DEFAULT 'BAN', "weekStartDate" TIMESTAMP(3) NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE("voterUserId", "targetUserId", "weekStartDate")); CREATE INDEX "ban_votes_targetUserId_weekStartDate_idx" ON "ban_votes" ("targetUserId", "weekStartDate");
CREATE TABLE "tasks" ("id" SERIAL PRIMARY KEY, "status" TEXT NOT NULL DEFAULT 'NOT_STARTED', "runnerClassName" TEXT NOT NULL, "runnerData" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "completedAt" TIMESTAMP(3), "storeId" TEXT, "lockTime" TIMESTAMP(3), "isNeverDeleted" BOOLEAN NOT NULL DEFAULT false, "isDeleted" BOOLEAN NOT NULL DEFAULT false); CREATE INDEX "tasks_status_idx" ON "tasks"("status"); CREATE INDEX "tasks_runnerClassName_idx" ON "tasks"("runnerClassName"); CREATE INDEX "tasks_completedAt_idx" ON "tasks"("completedAt"); CREATE INDEX "tasks_lockTime_idx" ON "tasks"("lockTime"); CREATE INDEX "tasks_isDeleted_idx" ON "tasks"("isDeleted");
CREATE TABLE "batches" ("id" SERIAL PRIMARY KEY, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "taskId" INTEGER NOT NULL REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE CASCADE); CREATE TABLE "batch_mappings" ("id" SERIAL PRIMARY KEY, "customId" TEXT NOT NULL UNIQUE, "batchId" INTEGER NOT NULL REFERENCES "batches"("id") ON DELETE CASCADE ON UPDATE CASCADE, "response" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "non_batches" ("id" SERIAL PRIMARY KEY, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "taskId" INTEGER NOT NULL REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE CASCADE); CREATE TABLE "non_batch_mappings" ("id" SERIAL PRIMARY KEY, "customId" TEXT NOT NULL UNIQUE, "response" TEXT, "nonBatchId" INTEGER NOT NULL REFERENCES "non_batches"("id") ON DELETE CASCADE ON UPDATE CASCADE, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "task_dependencies" ("id" SERIAL PRIMARY KEY, "taskId" INTEGER NOT NULL REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE CASCADE, "dependencyId" INTEGER NOT NULL REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE CASCADE, UNIQUE("taskId", "dependencyId"));
CREATE TABLE "openai_logs" ("id" SERIAL PRIMARY KEY, "userId" INTEGER REFERENCES "users"("id") ON UPDATE CASCADE, "taskId" INTEGER REFERENCES "tasks"("id") ON UPDATE CASCADE, "customId" TEXT NOT NULL UNIQUE, "storeId" TEXT NOT NULL, "runnerClassName" TEXT NOT NULL, "requestInitiated" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "responseReceived" TIMESTAMP(3), "requestData" TEXT NOT NULL, "responseData" TEXT, "errorMessage" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL); CREATE INDEX "openai_logs_userId_idx" ON "openai_logs"("userId"); CREATE INDEX "openai_logs_taskId_idx" ON "openai_logs"("taskId"); CREATE INDEX "openai_logs_runnerClassName_idx" ON "openai_logs"("runnerClassName"); CREATE INDEX "openai_logs_createdAt_idx" ON "openai_logs"("createdAt"); CREATE INDEX "openai_logs_storeId_idx" ON "openai_logs"("storeId");
CREATE TABLE "ai_results" ("id" SERIAL PRIMARY KEY, "customId" TEXT NOT NULL UNIQUE, "taskId" INTEGER REFERENCES "tasks"("id") ON DELETE SET NULL ON UPDATE CASCADE, "resultKind" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'PENDING', "result" JSONB, "errorMessage" TEXT, "requestInitiated" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "responseReceived" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL); CREATE INDEX "ai_results_taskId_idx" ON "ai_results"("taskId"); CREATE INDEX "ai_results_resultKind_idx" ON "ai_results"("resultKind");
CREATE TABLE "ai_result_sources" ("id" SERIAL PRIMARY KEY, "aiResultId" INTEGER NOT NULL REFERENCES "ai_results"("id") ON DELETE CASCADE ON UPDATE CASCADE, "ordinal" INTEGER NOT NULL, "url" TEXT NOT NULL, UNIQUE("aiResultId", "ordinal"), UNIQUE("aiResultId", "url"));
CREATE TABLE "global" ("id" SERIAL PRIMARY KEY, "worldGdp" DOUBLE PRECISION, "gasDistributionEnabled" BOOLEAN NOT NULL DEFAULT true, "salaryStatsUserCount" INTEGER NOT NULL DEFAULT 0, "salaryStatsTotal" DOUBLE PRECISION, "salaryStatsAverage" DOUBLE PRECISION, "salaryStatsMedian" DOUBLE PRECISION, "salaryStatsCalculatedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "gas_token_distributions" ("id" SERIAL PRIMARY KEY, "userId" INTEGER NOT NULL REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE, "network" TEXT NOT NULL, "amount" DECIMAL(65,30) NOT NULL, "backlogAmount" DECIMAL(65,30) NOT NULL DEFAULT 0, "amountUsd" DECIMAL(65,30) NOT NULL, "distributionDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "status" TEXT NOT NULL DEFAULT 'PENDING', "transactionHash" TEXT, "errorMessage" TEXT, "tokenType" TEXT NOT NULL DEFAULT 'NATIVE', "tokenSymbol" TEXT NOT NULL DEFAULT 'ETH', "tokenAddress" TEXT, "tokenDecimals" INTEGER NOT NULL DEFAULT 18, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, UNIQUE("userId", "network", "tokenSymbol", "distributionDate")); CREATE INDEX "gas_token_distributions_userId_idx" ON "gas_token_distributions"("userId"); CREATE INDEX "gas_token_distributions_network_idx" ON "gas_token_distributions"("network"); CREATE INDEX "gas_token_distributions_status_idx" ON "gas_token_distributions"("status"); CREATE INDEX "gas_token_distributions_distributionDate_idx" ON "gas_token_distributions"("distributionDate"); CREATE INDEX "gas_token_distributions_network_tokenSymbol_idx" ON "gas_token_distributions"("network", "tokenSymbol");
CREATE TABLE "gas_token_reserves" ("id" SERIAL PRIMARY KEY, "network" TEXT NOT NULL, "totalReserve" DECIMAL(65,30) NOT NULL DEFAULT 0, "lastDistribution" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "tokenType" TEXT NOT NULL DEFAULT 'NATIVE', "tokenSymbol" TEXT NOT NULL DEFAULT 'ETH', "tokenAddress" TEXT, "tokenDecimals" INTEGER NOT NULL DEFAULT 18, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, UNIQUE("network", "tokenSymbol", "tokenType"));
CREATE TABLE "system_secrets" ("id" SERIAL PRIMARY KEY, "name" TEXT NOT NULL UNIQUE, "value" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "pending_transactions" ("id" SERIAL PRIMARY KEY, "transactionHash" TEXT NOT NULL UNIQUE, "userId" INTEGER NOT NULL REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE, "network" TEXT NOT NULL, "recipientAddress" TEXT NOT NULL, "amount" DECIMAL(65,30) NOT NULL, "backlogAmount" DECIMAL(65,30) NOT NULL DEFAULT 0, "tokenType" TEXT NOT NULL, "tokenSymbol" TEXT NOT NULL, "tokenDecimals" INTEGER NOT NULL, "status" TEXT NOT NULL DEFAULT 'PENDING', "executionAttempts" INTEGER NOT NULL DEFAULT 0, "lastExecutionAttempt" TIMESTAMP(3), "executedTransactionHash" TEXT, "errorMessage" TEXT, "transactionData" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL); CREATE INDEX "pending_transactions_status_idx" ON "pending_transactions"("status"); CREATE INDEX "pending_transactions_network_idx" ON "pending_transactions"("network"); CREATE INDEX "pending_transactions_userId_idx" ON "pending_transactions"("userId"); CREATE INDEX "pending_transactions_createdAt_idx" ON "pending_transactions"("createdAt"); CREATE INDEX "pending_transactions_status_network_idx" ON "pending_transactions"("status", "network");

-- No persistent views or triggers were found. Temporary functions try_jsonb(TEXT) and
-- legacy_ai_result(JSONB) are created and dropped inside migration 20260711000000_compact_ai_results.
-- No CHECK constraints were found. SERIAL creates per-table sequences; CUID text IDs are generated by Prisma.
