[package]
name = "memory-collection-m1-compat"
version = "0.4.0-m1.1"
description = "A collection of data structures that store their data in stable memory"
repository = "https://github.com/NatLabs/memory-collection"
keywords = [ "stable-memory", "encoding", "persistent" ]
license = "MIT"

[dependencies]
"core@2.4" = "2.4.0"
"base@0.16" = "0.16.0"
"itertools@0.2" = "0.2.2"
"memory-region@1.5" = "1.5.0"
"buffer-deque@0.1" = "0.1.0"
"byte-utils@0.2" = "0.2.0"

[dev-dependencies]
test = "2.1.2"
bench = "2.0.1"
augmented-btrees = "0.9.0"
fuzz = "1.0.0"
stableheapbtreemap = "1.5.0"
map = "9.0.1"

[toolchain]
wasmtime = "43.0.0"
moc = "1.4.1"
