# See:
# https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/
# https://chatgpt.com/share/695d0a21-5718-8001-a9ad-20ef8f8e09d1

name: Deploy to Staging

on:
  push:
    branches: [main]

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    environment: staging  # CRITICAL

    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Intall
        run: |
          npm install
          npm run install-backend
          npm run install-frontend

      - name: Build
        run: npm run build  # redundant, but need check that it builds

      - name: Build
        run: (cd backend && npx prisma migrate status)  # TODO@P1: Ensure correct exit code.

      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.STAGING_DEPLOY_TOKEN }}
      - uses: actions/checkout@v4

      - name: Deploy to staging
        run: ./deploy/deploy-staging.sh
